[package]
name = "v_ikf"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.1.1", features = ["bundled"] }
libduckdb-sys = "1.1.1"
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
regex = "1.11.1"
